# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - prioridad:0
  - prioridad:1
  - update:core
# Label to use when marking an issue as stale
staleLabel: estado:expirada
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Esta issue se ha considerado expirada por no tener actividad reciente.
  Si sigue sin haber actividad, se cerrará automáticamente en una semana.
  ¿Trabajando en ella pero sin novedades? Tan solo comenta y refrescaré la issue.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Esta issue se ha cerrado automáticamente debido a inactividad.
  Si crees que esto ha sido un error, tan solo abrela de nuevo.